version: '3'
volumes:
  dbdata:
    external: true

networks:
  reverse-proxy:
    external: true

services:

  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: P1lluPallu!
      MYSQL_DATABASE: prestashop
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - reverse-proxy

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest # Latest stable version of the PrestaShop, to see all available images go to ...
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: P1lluPallu!
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true