version: '3'
volumes:
  mysqldb_data:
    external: true
  psdata:
    external: true
networks:
  reverse-proxy:
    external: true

services:

  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: P1lluPallu!
      MYSQL_DATABASE: prestashop
    volumes:
      - mysqldb_data:/var/lib/mysql
    networks:
      - reverse-proxy

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest # Latest stable version of the PrestaShop, to see all available images go to ...
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: P1lluPallu!
      PS_INSTALL_AUTO: 1
      #PS_DOMAIN: ps.actek.ovh
    networks:
      - reverse-proxy
    volumes:
      - type: bind
        source: ./modules/testModule # local path to the module
        target: /var/www/html/modules/testModule # path to be mounted in the container
      - type: bind
        source: ./themes/myTheme # local path to the theme
        target:  /var/www/html/themes/myTheme # path to be mounted in the container
      - psdata:/var/www/html

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      links:
        - mysql
      environment:
        PMA_HOST: some-mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        PMA_USER: root
        PMA_PASSWORD: P1lluPallu!
      restart: unless-stopped
      ports:
        - 8081:80
      networks:
        - reverse-proxy